/**
 * Resolves the public base URL of the FairTab web application.
 * On mobile/native builds, window.location.origin is "https://localhost" or "capacitor://localhost".
 * This helper ensures invite and verification links generated by the app always point to the canonical public web deployment.
 */
export function getPublicAppBaseUrl(): string {
  // Always use the canonical Firebase Hosting production URL for links
  return "https://fairtab-48340.web.app";
}

/**
 * Builds a canonical hash-routed link for the application.
 * @param hashPath Path after hash (e.g. "/join/abc123" or "/invite/xyz")
 */
export function buildPublicAppLink(hashPath: string): string {
  const base = getPublicAppBaseUrl();
  const normalizedPath = hashPath.startsWith("/") ? hashPath : `/${hashPath}`;
  return `${base}#${normalizedPath}`;
}
