/**
 * Resolves the public base URL of the FairTab web application.
 * On mobile/native builds, window.location.origin is "https://localhost" or "capacitor://localhost".
 * This helper ensures invite and verification links generated by the app always point to the canonical public web deployment.
 */
export function getPublicAppBaseUrl(): string {
  // If running in browser and NOT localhost/capacitor, use current origin + pathname
  if (typeof window !== "undefined" && window.location) {
    const origin = window.location.origin;
    const isLocal = origin.includes("localhost") || origin.includes("127.0.0.1") || origin.includes("capacitor://");
    if (!isLocal) {
      // Clean trailing slashes or hash
      const cleanPath = window.location.pathname.replace(/\/+$/, "");
      return `${origin}${cleanPath}`;
    }
  }

  // Canonical production web deployment URL (Firebase Hosting)
  return "https://fairtab-48340.web.app";
}

/**
 * Builds a canonical hash-routed link for the application.
 * @param hashPath Path after hash (e.g. "/join/abc123" or "/invite/xyz")
 */
export function buildPublicAppLink(hashPath: string): string {
  const base = getPublicAppBaseUrl();
  const normalizedPath = hashPath.startsWith("/") ? hashPath : `/${hashPath}`;
  return `${base}#${normalizedPath}`;
}
