/// <reference lib="webworker" />
import { precacheAndRoute, cleanupOutdatedCaches } from "workbox-precaching";

declare const self: ServiceWorkerGlobalScope;

// Cleanup old caches from previous versions
cleanupOutdatedCaches();

// Precache all assets listed in the manifest generated by Vite PWA plugin
precacheAndRoute(self.__WB_MANIFEST);

self.addEventListener("install", () => {
  // Force activation of the service worker immediately
  self.skipWaiting();
});

self.addEventListener("activate", (event) => {
  event.waitUntil(self.clients.claim());
});

// Implement a basic fallback for navigation when offline and not cached
self.addEventListener("fetch", (event) => {
  if (event.request.mode === "navigate") {
    event.respondWith(
      fetch(event.request).catch(async () => {
        const cachedResponse = await caches.match("/FairTab/offline.html") || await caches.match("offline.html");
        return cachedResponse || new Response("Offline Fallback", {
          status: 503,
          headers: { "Content-Type": "text/html" }
        });
      })
    );
  }
});
